function [YEARS,MONTHS,DAYS,HOURS,MINUTES,SECONDS]=time2impact(t)

if t<=2*365*24*3600
    YEAR=floor(t/(365*24*3600));
    year=2018+YEAR;
    day=(t/(365*24*3600)-floor(t/(365*24*3600)))*365;
else
    YEAR=floor((t-24*3600)/(365*24*3600));
    year=YEAR+2018;
    day=((t-24*3600)/(365*24*3600)-floor((t-24*3600)/(365*24*3600)))*365;
end
if year==2020
    if day<=31
        MONTH=0;
        DAY=floor(day);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>31 && day<=60
        MONTH=1;
        DAY=floor(day-31);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>60 && day<=91
        MONTH=2;
        DAY=floor(day-60);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>91 && day<=121
        MONTH=3;
        DAY=floor(day-91);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>121 && day<=152
        MONTH=4;
        DAY=floor(day-121);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>152 && day<=182
        MONTH=5;
        DAY=floor(day-152);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>182 && day<=213
        MONTH=6;
        DAY=floor(day-182);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>213 && day<=244
        MONTH=7;
        DAY=floor(day-213);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>244 && day<=274
        MONTH=8;
        DAY=floor(day-244);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>274 && day<=305
        MONTH=9;
        DAY=floor(day-274);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>305 && day<=335
        MONTH=10;
        DAY=floor(day-305);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>335
        MONTH=11;
        DAY=floor(day-335);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    end
else
    if day<=31
        MONTH=0;
        DAY=floor(day);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>31 && day<=59
        MONTH=1;
        DAY=floor(day-31);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>59 && day<=90
        MONTH=2;
        DAY=floor(day-59);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>90 && day<=120
        MONTH=3;
        DAY=floor(day-90);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>120 && day<=151
        MONTH=4;
        DAY=floor(day-120);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>151 && day<=181
        MONTH=5;
        DAY=floor(day-151);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>181 && day<=212
        MONTH=6;
        DAY=floor(day-181);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>212 && day<=243
        MONTH=7;
        DAY=floor(day-212);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>243 && day<=273
        MONTH=8;
        DAY=floor(day-243);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>273 && day<=304
        MONTH=9;
        DAY=floor(day-273);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>304 && day<=334
        MONTH=10;
        DAY=floor(day-304);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    elseif day>334
        MONTH=11;
        DAY=floor(day-334);
        HOUR=floor((day-floor(day))*24);
        MINUTE=floor(((day-floor(day))*24-HOUR)*60);
        SECOND=floor((((day-floor(day))*24-HOUR)*60-MINUTE)*60);
    end
end
YEARS=YEAR;
MONTHS=MONTH;
DAYS=DAY;
HOURS=HOUR;
MINUTES=MINUTE;
SECONDS=SECOND;
